# Generated by Django 6.0.3 on 2026-03-13 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='🧒', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('temps_total', models.IntegerField(default=0)),
                ('terminee', models.BooleanField(default=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='app.enfant')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('icone', models.CharField(default='⭐', max_length=10)),
                ('ordre', models.IntegerField(default=1)),
                ('terminee', models.BooleanField(default=False)),
                ('enfant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='app.enfant')),
            ],
        ),
    ]
